# Site settings
title: Solace Samples C#/.NET
summary: These tutorials get you up to speed sending and receiving messages with Solace technology.
baseurl: "/solace-samples-dotnet" # the subpath of your site, e.g. /solace-samples-java
repository: https://github.com/SolaceSamples/solace-samples-dotnet

# Also see _includes/intro.html to customize the description which gets included in index.html.

# Links
links-downloads: //dev.solace.com/downloads/
links-community: //dev.solace.com/community/
links-get-started: //dev.solace.com/get-started/dotnet-tutorials/
links-solaceCloud-setup: //cloud.solace.com/create-messaging-service/
docs-core-concepts: //docs.solace.com/Features/Core-Concepts.htm
docs-endpoints: //docs.solace.com/Features/Core-Concepts.htm#endpoints
docs-api-concepts: //docs.solace.com/Features/Core-Concepts.htm#api-concepts
docs-solace-apis: //docs.solace.com/Solace-Messaging-APIs/Solace-APIs-Overview.htm
docs-gm-rr: //docs.solace.com/Solace-Messaging-APIs/Request-Reply-Messaging.htm
docs-topic-queue: //docs.solace.com/Features/Core-Concepts.htm#topic-queue-mapping
docs-dotnet: //docs.solace.com/Solace-Messaging-APIs/net-api-home.htm
docs-client-profile: //docs.solace.com/Features/Core-Concepts.htm#client-profile
docs-dotnet-api: //docs.solace.com/API-Developer-Online-Ref-Documentation/net/index.html
